### ISSUE TITLE
can't load a config file created by libconf

### ISSUE THREAD

**Issue by awoodx** [Grk0/python-libconf#15]
Hi, 
I'm having issues with libconf.load()'ing a file that I created using libconf.dump(). A small snippet that reproduces the issue:

```python
import libconf
t1 = {}
t1["test"] = []
pset = {}
pset["param1"] = "x";
t1["test"].append(pset)
t1["test"].append(pset)
s = libconf.dumps(t1)
lc = libconf.loads(s)
```
I get libconf.ConfigParseError:
libconf.ConfigParseError: Unexpected token u'{' in '<unknown>', row 3, column 5; expected: (']',)
Any help or workaround would be greatly appreciated!

**Comment by Grk0** [comment]
Python-libconf maps Python Lists to [Libconfig Arrays](https://hyperrealm.github.io/libconfig/libconfig_manual.html#Arrays) and Python Tuples To [Libconfig Lists](https://hyperrealm.github.io/libconfig/libconfig_manual.html#Lists). The idea behind this was to match Python syntax to Libconfig syntax:

* Python List `[]` <-> Libconfig Array `[]`
* Python Tuple `()` <-> Libconfig List `()`

The catch is that Libconfig Array elements must be scalar values of the same type. I.e. `[1,2,3]` is valid, but `[1,2,true]` is not, neither is `[{key: "value"}]` since the element is not a scalar type but a group. This is the issue you're seeing.

I feel that there is a bit of friction around this Python Tuple <-> Libconfig List mapping, but I don't have a great idea on how to resolve it. A simple solution would be to validate the "scalar values of constant type" constraint in `dumps()`. I don't want to go too deep into output validation, but this seems to be a common enough issue to warrant a fix.

What's your opinion?

**Comment by awoodx** [comment]
I see.. yeah, I suppose you would need to check if all elements in the list are scalar values, and then decide whether to write as a LibConfig Array or List. 

Personally, I don't like using tuples since I'm also using json.loads/dumps, and the json library doesn't support natively support tuples.
