### ISSUE TITLE
Edit Config?

### ISSUE THREAD

**Issue by cliffburdick** [Grk0/python-libconf#16]
Is there a way to edit a nested field to set a tuple value? For example, say after reading it in, I have:

a.b[0].c[0].d = ((1,2),(3,4))

I can see c[0] is an AttrDict (this was confusing because there's a publicly-available AttrDict, but it looks like libconf defines its own). If I want to set d again, I do:

a.b[0].c[0].d = ((2,2),(4,4))

If I print a.b[0].c[0].d, the value is correct. However, if I print a, the values I wrote are gone. Is this intended?

**Comment by ChrisAichinger** [comment]
I wouldn't say it's intended this way, I'm unsure of what the ideal behavior would be.

The correct way to set the attribute would be `a.b[0].c[0]['d'] = ((2,2),(4,4))`, so using the item accessor, not the attribute accessor. This is in line with e.g. how Pandas works: you can access `dataframe.xyz`, but to assign column `xyz`, you'd have to write `dataframe['xyz'] = 42`.

Extending the built-in AttrDict would not be particularly hard, but I'm wondering whether it's the correct solution. It just moves the problem elsewhere: `ad.d = 7` would now work, but what about assignments that would overwrite `dict` member functions, such as `ad.keys = 7`?

The best way seems to be to handle it like Pandas: the `container.item` syntax is a convenient short-hand for `container['item']`, but with strong limitations. Whenever a potential conflict occurs (assignment, clash with existing member functions, ...) you need to revert to the non-short-hand version. That's already how it works today. 

If you think otherwise, please let me know.

**Comment by cliffburdick** [comment]
@Grk0 I've since left the company where I used this, so if you want to close it I wouldn't mind.
