### ISSUE TITLE
Settings starting with a number fails to parse

### ISSUE THREAD

**Issue by t-kky** [Grk0/python-libconf#21]
I ran into this library as I was trying to parse large libconfig files not created by me. In these files, it is common that settings with names that start with a digit appear. This library is currently unable to parse these files properly. I don't know whether or not these names are technically allowed or not in libconfig, but it's how they appear in the files I have.

At first I did not understand that this was the issue. After a bit of digging into the code, I was able to make the file(s) parse properly. I can't say I understand all of it very well, but this is what I did:

The `tokenizer` will match expressions in the `token_map`. As soon as it finds a match, it returns it as a token. When it runs into a setting name such as "3rd_day", it will match the integer expression and return. This breaks parsing the rest of the file when the integer belongs to the name of a setting.

I changed the integer match expression to require that a letter does not directly follow the digits. This should be okay since hex values and int64 values will already have been tried before it tries to match regular integers.

I changed the integer expression from
```
(IntToken, "integer", r"[-+]?[0-9]+"),
```
to
```
(IntToken, "integer", r"[-+]?[0-9]+(?![A-Za-z])"),
```

I also modified the name expression to allow for a digit by changing from
```
(Token, "name", r"[A-Za-z\*][-A-Za-z0-9_\*]*"),
```
to
```
(Token, "name", r"[A-Za-z0-9\*][-A-Za-z0-9_\*]*"),
```

I don't know whether or not this solution is robust. Regex is not my thing. I also don't know whether or not these types of setting names should be allowed, but since I have files full of them I require this modification.

**Comment by ChrisAichinger** [comment]
If I understand correctly, these files are not compliant with the libconfig format. The specification doesn't detail how a `name` should look like, but the C reference implementation [doesn't allow names starting with digits](https://github.com/hyperrealm/libconfig/blob/5ea446216255e90bfdbf646a06404e37651f192b/lib/scanner.l#L59). Consequently, this isn't something that I would want to include in python-libconf.

I completely understand your predicament though. The simplest solution is to copy `libconf.py` into your source code tree, and make the necessary modifications there. I keep libconf as a single-file library exactly for this use-case. So instead of pulling in libconf via PyPI, you'd commit the main file -- `libconf.py` -- into your own git repository. I hope this helps. 

If you're OK with it, I would suggest closing this issue. If I misunderstood anything, please let me know!

**Comment by t-kky** [comment]
You are correct. I ran into more issues. The files I have make use of a special multi line string that start with `<"` and end with `">`. Once again I think I was able to make the library work by adding some regex. I will do as you suggest and include the `libconf.py` file with the modifications. The fact that there are no dependencies is very nice!

I will close this issue. Thanks for the reply!
