### ISSUE TITLE
load() only works for Python 3

### ISSUE THREAD

**Issue by jwiegley** [Grk0/python-libconf#4]
The following code in libconf.py:

``` python
    if isinstance(f.read(0), bytes):
        raise TypeError("libconf.load() input file must by unicode")
```

Only works for file objects opened in Python 3.  It should be something like:

``` python
if sys.version_info >= (3,0,0):
    # for Python 3
    if isinstance(s, bytes):
        raise TypeError("libconf.load() input file must be unicode")
else:
    # for Python 2
    if isinstance(s, unicode):
        raise TypeError("libconf.load() input file must be unicode")
```

Including @tgiannak, who found this issue.

**Comment by jwiegley** [comment]
This replacement code came from: http://stackoverflow.com/questions/4987327/how-do-i-check-if-a-string-is-unicode-or-ascii

**Comment by Grk0** [comment]
Thanks for using libconf and for taking the time to report this!

Could you please provide a code snippet of how you're using libconf and what the error message is? There are several tests in ``test/test_e2e.py`` that pass on [Travis](https://travis-ci.org/Grk0/python-libconf) running on Python 2.7 (there is a [``bytes`` alias for ``str``](http://stackoverflow.com/a/5901825/25097) since 2.6). I'm not sure how your usage differs. Getting to the bottom of it would be interesting, maybe we can improve the overall situation for Python 2.7 users a bit. The strict ``unicode`` requirement is probably relatively uncommon on 2.7.

**Comment by jwiegley** [comment]
This test code (after creating the named file with some content) shows the situation, since it's exactly the sort of check that `libconf` is making:

``` python
with open('scraper_mon.cfg') as f:
    contents = f.read()
    f.seek(0)
    if isinstance(f.read(0), bytes):
        raise TypeError("FAILED")
```

This works fine if run under Python 3, but not 2.7 here.  Sadly, I can't include the full test, since it's part of an internal project.  Thanks!

**Comment by Grk0** [comment]
Could you try ``io.open()``? The builtin ``open()`` produces ``bytes`` objects on Python2, while libconf expects ``unicode``. The unicode requirement is [documented](https://github.com/Grk0/python-libconf#character-encoding-and-escape-sequences), though I see that my own example in README.md is wrong (using the builtin ``open()``).

**Comment by jwiegley** [comment]
With `io.open` it seems to work.

**Comment by Grk0** [comment]
Hi @jwiegley, is it OK if I close this issue? ``io.open()`` works and release 1.01 fixes the documentation bug in README.rst. If you have any further issues with libconf's unicode handling on Python2, we can always open a followup issue.
